name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Use GitHub Secrets for your service account key
          project_id: hale-equator-435411  # Your project ID
          export_default_credentials: true

      - name: Deploy to Google Cloud Storage
        run: |
          gsutil cp -r ./* gs://chatsach/
