jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "hale-equator-435411"
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_KEY_FILE }}
      - name: Upload to GCS bucket
        run: gsutil cp your-file.txt gs://chatsach/
